all: log_builder score_builder

log_builder: log_builder.cpp
	g++ --std=c++11 -O2 -Wall log_builder.cpp -o log_builder

score_builder: score_builder.cpp
	g++ --std=c++11 -O2 -Wall score_builder.cpp -o score_builder
